### ISSUE TITLE
[FIX, FEAT]  Sprint 1: 포인트 정책 제거, 장바구니, 장바구니 기능 결제 api에 적용, 상세 페이지 이미지

### ISSUE THREAD

**Issue by 05AM** [TEAM-TATTOUR/tattour-server#140]
## 🦋 Feature Issue

- 포인트 정책 로직 제거
- 장바구니
- 장바구니 기능 결제 api에 적용

## ✅ To-do

- [x] 포인트 정책 로직 제거
- [x] 유저 장바구니 목록 불러오기 api
- [x] 장바구니 생성 api
- [x] 장바구니 수량 수정 api
- [x] 장바구니 삭제 api
- [x] 결제 페이지 불러오기 api
  - 장바구니에서 불러오기
- [x] 결제하기 api
  - 장바구니에서 불러오기
  - 결제 완료 후 장바구니 목록 삭제
- [x] 장바구니 순서 정렬
- [x] 상세 페이지 이미지
- [ ] 결제 시 발송되는 디스코드 메시지 수정 (단일 상품 정보 -> 복수 상품 정보 포함)
