### ISSUE TITLE
[FIX, REFACTOR] SP1 리팩토링 및 버그 수정

### ISSUE THREAD

**Issue by 05AM** [TEAM-TATTOUR/tattour-server#156]
## 🦋 Feature Issue

> SP1 리팩토링 및 버그 수정

## ✅ To-do

- [ ] 인증번호 API 응답 시간 기록 및 성능 최적화
- [x] jwt 토큰 만료 시간 수정
- [ ] 디스코드 메시지 형식 수정
- [ ] 임시저장 커스텀 도안 이름 수정 - 날짜:시간 형식으로
- [ ] 임시저장 커스텀 도안 순서 정렬
