### ISSUE TITLE
[BUG] logback-spring.xml 파일 추가 후 cd 실패 문제

### ISSUE THREAD

**Issue by 05AM** [TEAM-TATTOUR/tattour-server#26]
## 🦋 Bug

- logback-spring.xml 파일 추가 후 cd 실패하는 버그가 발생했습니다.
- deploy를 수행하는 user에 권한이 없어 발생하는 문제로 보입니다.

## ✅ To-do

- [x] codedeploy-agent user를 찾아 권한 부여하기
- [x] cd 성공 확인하기
- [x] java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
