### ISSUE TITLE
[FEAT] 관리자 스티커 등록 api , 커스텀 도안 신청 받기 ( status 변경하기 ) api

### ISSUE THREAD

**Issue by SeorinY** [TEAM-TATTOUR/tattour-server#34]
## 🦋 Feature Issue

- 관리자 api 추가

## ✅ To-do

- [x] 관리자 스티커 등록 api
- [x] 커스텀 도안 신청 받기 ( status 변경하기 ) api
- [ ] 커스텀 도안 신청 에러 다듬기
