### ISSUE TITLE
[REFACTOR] 리팩토링

### ISSUE THREAD

**Issue by 05AM** [TEAM-TATTOUR/tattour-server#57]
## 🦋 Feature Issue

- 리팩토링

## ✅ To-do

- [x] 포인트 로그 title enum형으로 관리하기
- [x] service / controller dto 네이밍 룰 정하고 이름 일괄 변경하기
- [ ] service, controller dto 완전 분리하기
- [x] entity를 get하는 서비스 함수들 더 좋은 방법 찾기
- [x] facade 패턴 적용
