### ISSUE TITLE
[FEAT] user, phone_number_verification_code, product_liked, order, point_charge_request, user_point_log, user_shipping_address 엔티티 생성

### ISSUE THREAD

**Issue by 05AM** [TEAM-TATTOUR/tattour-server#7]
## 🦋 Feature Issue

- user, phone_number_verification_code, product_liked, order, point_charge_request, user_point_log, user_shipping_address 엔티티 생성

## ✅ To-do

- [x] user
- [x] phone_number_verification_code
- [x] product_liked
- [x] order
- [x] point_charge_request
- [x] user_point_log
- [x] user_shipping_address
